spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cars?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    database-platform: 'org.hibernate.dialect.MySQL5InnoDBDialect'
    hibernate.use-new-id-generator-mappings: false
    show-sql: false
    properties :
      hibernate:
       format_sql: true
  h2.console.enabled: true
  main:
   allow-bean-definition-overriding: true

cars:
  ford:
    ingester:
      runCron: 0 * * ? * * 